version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
